package com.neotys.neoload.model.v3.writers.neoload.userpath;

import com.neotys.neoload.model.v3.project.userpath.Case;
import com.neotys.neoload.model.v3.writers.neoload.ElementWriter;
import com.neotys.neoload.model.v3.writers.neoload.SlaElementWriter;
import com.neotys.neoload.model.v3.writers.neoload.WriterUtils;
import org.w3c.dom.Document;
import org.w3c.dom.Element;

import java.util.Optional;

public class CaseWriter extends ElementWriter {
    private static final String XML_TAG_NAME = "case-statement";
    private static final String XML_ATTR_CASE_BREAK = "case-break";
    private static final String XML_ATTR_VALUE = "case-value";
    private static final String XML_ATTR_CASE_UID = "case-uid";


    private static final String XML_ELEMENT_NUMBER = "element-number";
    private static final String XML_EXECUTION_TYPE = "execution-type";
    private static final String XML_WEIGHTS_ENABLED = "weightsEnabled";

    private static final String DEFAULT_ELEMENT_NUMBER = "1";
    private static final String DEFAULT_EXECUTION_TYPE = "0";
    private static final String DEFAULT_WEIGHTS_ENABLED = "false";

    public CaseWriter(final Case aCase) {
        super(aCase);
    }

    public static CaseWriter of(final Case aCase) {
        return new CaseWriter(aCase);
    }

    @Override
    public void writeXML(final Document document, final Element currentElement, final String outputFolder) {
        final Element caseElement = document.createElement(XML_TAG_NAME);
        caseElement.setAttribute(XML_ATTR_CASE_BREAK, String.valueOf(((Case) element).isBreak()));
        caseElement.setAttribute(XML_ATTR_CASE_UID, WriterUtils.getElementUid(element));
        caseElement.setAttribute(XML_ATTR_VALUE, ((Case) element).getValue());
        /*
        To respect the syntax of the XML generated by NEOLOAD
        We don't have to write the attributes name so this is why we don't use the super constructor
         */
        caseElement.setAttribute(XML_ELEMENT_NUMBER, DEFAULT_ELEMENT_NUMBER);
        caseElement.setAttribute(XML_EXECUTION_TYPE, DEFAULT_EXECUTION_TYPE);
        caseElement.setAttribute(XML_WEIGHTS_ENABLED, DEFAULT_WEIGHTS_ENABLED);
        currentElement.appendChild(caseElement);
        final Case aCase = ((Case) this.element);
        SlaElementWriter.of(aCase).writeXML(caseElement);
        writeDescription(document, caseElement);
        /*
        For respect the xml create by neoload, we have to fill the body of the case statement
        But We don't have to write the Steps at the end of the case-statement
        This will be done in the Switch Writer
         */
        ((Case) element).getSteps().forEach(
                elt -> WriterUtils.generateEmbeddedAction(document, caseElement, elt, Optional.of(WriterUtils.WEIGHTED_ACTION_XML_TAG_NAME), true)
        );
    }
}
