name: Main Workflow (build & tests)
on:
  push:
    branches: [ v3 ]
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8.0
    - name: Build with Maven
      run: mvn -B package --file pom.xml
